version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/opt/application/autozapi
    ports:
      - '3333:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
